# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "http://gyani.net"
baseurl: ""

# Brief name and description of the site
title: Gyanendra Mishra
description: "Undergraduate Computer Science student. Loves all things data and security. I will code for airtickets."

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 5
paginate_path: "/page:num/"

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/gyani.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Projects: "projects"
  About: "about"
  Achievements: "achievements"
  Ideas: "ideas"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Gyanendra Mishra
  email: "anomaly.the@gmail.com"
  facebook: iownfb
  github: h4ck3rk3y
  twitter: _gyani_
  linkedin: in/mishragyanendra
  stackoverflow: users/3978786/gyanendra-mishra
  tumblr: 0x-gyani

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: true
  stackoverflow: false
  tumblr: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "gyani.net"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "gyani"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-60799114-1"  # Your Google Analytics ID
fb_app_id: 201438500215535

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
      show-share: true # add sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# 2fc73a3a967e97599c9763d05e564189
